log -r /tb/u_system/u_amber/u_fetch/*
log -r /tb/u_system/u_amber/u_mem/*
log -r /tb/u_system/u_amber/u_execute/*
log -r /tb/u_system/u_amber/u_wishbone/*
log /tb/u_system/u_amber/u_execute/u_register_bank/*
log /tb/u_system/u_amber/u_decode/*
log /tb/u_system/boot_mem128/u_boot_mem/*


log /tb/clk_count
log /tb/u_system/u_uart0/i_uart_rxd
log /tb/u_system/u_uart0/rx_fifo
log /tb/u_system/u_uart0/fifo_enable
log /tb/u_system/u_uart0/rx_fifo_push
log /tb/u_system/u_uart0/rx_fifo_push_not_full
log /tb/u_system/u_uart0/rx_byte
log /tb/u_system/u_uart0/xRXD_STATE
log /tb/u_system/u_uart0/TX_BITADJUST_COUNT
log /tb/u_system/u_uart0/TX_BITPULSE_COUNT
log /tb/u_system/u_uart0/xTXD_STATE
log /tb/u_tb_uart/i_uart_rxd
log /tb/u_tb_uart/o_uart_txd
log /tb/u_tb_uart/rx_bit_count
log /tb/u_tb_uart/rx_bit_start
log /tb/u_tb_uart/rx_byte
log /tb/u_system/ddr3_addr
log /tb/u_system/ddr3_ba
log /tb/u_system/ddr3_cas_n
log /tb/u_system/ddr3_ck_n
log /tb/u_system/ddr3_ck_p
log /tb/u_system/ddr3_cke
log /tb/u_system/ddr3_dm
log /tb/u_system/ddr3_dq
log /tb/u_system/ddr3_dqs_n
log /tb/u_system/ddr3_dqs_p
log /tb/u_system/ddr3_odt
log /tb/u_system/ddr3_ras_n
log /tb/u_system/ddr3_reset_n
log /tb/u_system/ddr3_we_n
log /tb/u_system/u_amber/fetch_stall
log /tb/u_system/u_amber/u_fetch/o_fetch_stall
log /tb/u_system/u_amber/u_fetch/sel_cache
log /tb/u_system/u_amber/u_fetch/u_cache/o_stall
log /tb/u_system/u_amber/u_fetch/u_cache/read_stall
log /tb/u_system/u_amber/u_fetch/u_cache/o_wb_req
log /tb/u_system/u_amber/u_fetch/u_cache/xC_STATE
log /tb/u_system/u_amber/u_fetch/u_cache/miss_address
log /tb/u_system/u_amber/u_fetch/u_cache/read_miss
log /tb/u_system/u_amber/u_fetch/u_cache/o_read_data
log /tb/u_system/u_amber/u_coprocessor/o_cache_enable
log /tb/u_system/u_amber/u_fetch/u_cache/i_core_stall
log /tb/u_system/u_amber/u_fetch/u_cache/i_select
log /tb/u_system/u_amber/u_fetch/sel_cache
log /tb/u_system/u_amber/u_fetch/u_cache/tag_wdata
log /tb/u_system/u_amber/u_fetch/u_cache/tag_address
log /tb/u_system/u_amber/u_fetch/u_cache/tag_wenable
log /tb/u_system/u_amber/u_decode/xMODE
log /tb/u_system/u_amber/u_decode/xCONTROL_STATE
log /tb/u_system/u_amber/u_decode/instruction_execute
log /tb/u_system/u_amber/u_decode/interrupt
log /tb/u_system/u_amber/u_decode/mtrans_num_registers
log /tb/u_system/u_amber/u_decode/pre_fetch_instruction_wen
log /tb/u_system/u_amber/u_decode/instruction
log /tb/u_system/u_amber/u_decode/instruction_valid
log /tb/u_system/u_amber/u_decode/saved_current_instruction_wen
log /tb/u_system/u_amber/u_decode/use_saved_current_instruction
log /tb/u_system/u_amber/u_decode/pc_wen_nxt
log /tb/u_system/u_amber/u_decode/write_pc
log /tb/u_system/u_amber/u_execute/execute
log /tb/u_system/u_amber/u_decode/u_decompile/xINSTRUCTION_EXECUTE
log /tb/u_system/u_amber/u_execute/i_pc_sel
log /tb/u_system/u_amber/u_execute/pc_wen
log /tb/u_system/u_amber/u_execute/pc_nxt
log /tb/u_system/u_amber/u_execute/rn
log /tb/u_system/u_amber/u_execute/u_register_bank/r15
log /tb/u_system/u_amber/u_decode/instruction_execute
log /tb/u_system/u_amber/u_decode/pre_fetch_instruction
log /tb/u_system/u_amber/u_decode/u_decompile/xINSTRUCTION_EXECUTE
log /tb/u_system/u_amber/u_decode/xCONTROL_STATE
log /tb/u_system/u_amber/u_decode/xMODE
log /tb/u_system/u_amber/u_execute/i_pc_sel
log /tb/u_system/u_amber/u_decode/o_pc_wen
log /tb/u_system/u_amber/u_decode/u_decompile/execute_valid
log /tb/u_system/u_amber/u_execute/u_register_bank/r14_irq
log /tb/u_system/u_amber/u_execute/pc
log /tb/u_system/u_amber/u_execute/pc_wen
log /tb/u_system/u_amber/u_execute/i_pc_sel
log /tb/u_system/u_amber/u_execute/alu_out
log /tb/u_system/u_amber/u_execute/i_status_bits_flags_wen
log /tb/u_system/u_amber/u_execute/status_bits_flags
log /tb/u_system/u_amber/u_execute/i_status_bits_sel
log /tb/u_system/u_amber/u_execute/i_condition
log /tb/u_system/u_amber/u_execute/execute
log /tb/u_system/u_amber/o_wb_cyc
log /tb/u_system/u_amber/o_wb_stb
log /tb/u_system/u_amber/i_wb_ack
log /tb/u_system/u_amber/o_wb_dat
log /tb/u_system/u_amber/o_wb_sel
log /tb/u_system/u_amber/o_wb_we
log /tb/u_system/u_amber/i_wb_dat
log /tb/u_system/u_amber/i_wb_err
log /tb/u_system/u_amber/u_coprocessor/fault_address
log /tb/u_system/u_amber/u_coprocessor/fault_status

run -all
